#!/usr/bin/env bash
# 5-dont_stop_me_nowBash script that stops 4-to_infinity_and_beyond process.

PID=$(pgrep -o -f  "bash 4-to_infinity_and_beyond" )

if [[ -n $PID ]]; then
    kill -ls "$PID"
    fi
