#!/usr/bin/env bash
#script that displays clock from 1 to 12

h=0

while [ $h -le 12 ]; do
	echo "Hour: $h"
	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done

	((h++))
done
