#!/usr/bin/env bash
#check for fike and print message

file_path="school"

if [ -e "$file_path" ]; then
    echo "school file exits"

    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    
    else
        echo "school file os empty"
    fi
    
    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
