#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
#localhost resolved to 127.0.0.2
#facebook resolved to 8.8.8.8

cp /etc/hosts ~/hosts.new_host
echo "127.0.0.2	localhost" > ~/hosts.new_host
echo "8.8.8.8	facebook.com" ~/hosts.new_host
cp -f ~/hosts.new_host /etc/hosts
